### ISSUE TITLE
Units under offensive general try to shoot up when they are not suppose to

### ISSUE THREAD

**Issue by michal-mad** [notsure8x/e2140-unofficial-patch#3]
Units such as SPIDER or TIGER HELLMAKER shoot up (target enemy helicopters) when under offensive general mode. Damage is not dealt but it's clearly visible that such units aim and shoot at flying enemy units.

**Comment by notsure8x** [comment]
@michal-mad can you attach save game or mission number where this can be easily reproduced? Also do you know if same behaviour exists in DOS version?

**Comment by michal-mad** [comment]
When you load that save you should immediately see SPIDER shooting at orange helicopter. It's not super easy to reproduce though. It seems that on different maps it's harder, on some it's easier (or it's just an impression - hard to say).

I did not check how DOS behaves. It may be an old bug but tbh I highly doubt it.

[save3.zip](https://github.com/notsure8x/e2140-unofficial-patch/files/13729786/save3.zip)

**Comment by notsure8x** [comment]
@michal-mad I converted your save game to DOS version and reproduced this issue. It was quite common in vanilla version for ED units like HT34J or Android A3 to shoot their ion cannons at the air units, Spider I is not exception here. I would consider this as a feature, not a bug. What could be improved though is that for sure HellMaker shouldn't try shoot air units because it doesn't make sense. I can imagine energy weapons to be fast enough to intercept aircraft but napalm canisters/granades definitely not.

![image](https://github.com/notsure8x/e2140-unofficial-patch/assets/147976982/117f39d7-5158-4265-9d3b-b9b0a7782473)

Extra comment for no damage - all those units can actually damage enemy aircraft, but it's a roll dice. If you try play your save game multiple times or long enough,  those Spiders will eventually score a hit and destroy this Storm helicopter in one shot.

**Comment by michaeldgg2** [comment]
Here it is, in its full glory: ground units, which are not supposed to attack air units, are attacking enemy airborne units:

<a href="https://dalek.zone/w/5kZzdDqGvNak3BiwK9HGdk"><p><img src="https://dalek.zone/lazy-static/previews/1e5f1f56-fae2-4737-a227-2a878f0c090d.jpg"></p><p>https://dalek.zone/w/5kZzdDqGvNak3BiwK9HGdk</p></a>
